# -*- coding: utf-8 -*-
currencymap = {
 "DZD": "Algerian Dinar"
,"NAD": "Namibian Dollar"
,"GHS": "Ghanaian Cedi"
,"EGP": "Egyptian Pound"
,"BGN": "Bulgarian Lev"
,"PAB": "Panamanian Balboa"
,"BOB": "Bolivian Boliviano"
,"DKK": "Danish Krone"
,"BWP": "Botswanan Pula"
,"LBP": "Lebanese Pound"
,"TZS": "Tanzanian Shilling"
,"VND": "Vietnamese Dong"
,"AOA": "Angolan Kwanza"
,"KHR": "Cambodian Riel"
,"MYR": "Malaysian Ringgit"
,"KYD": "Cayman Islands Dollar"
,"LYD": "Libyan Dinar"
,"UAH": "Ukrainian Hryvnia"
,"JOD": "Jordanian Dinar"
,"AWG": "Aruban Florin"
,"SAR": "Saudi Riyal"
,"LTL": "Lithuanian Litas"
,"HKD": "Hong Kong Dollar"
,"CHF": "Swiss Franc"
,"GIP": "Gibraltar Pound"
,"BYR": "Belarusian Ruble"
,"ALL": "Albanian Lek"
,"BYN": "New Belarusian Ruble"
,"MRO": "Mauritanian Ouguiya"
,"HRK": "Croatian Kuna"
,"DJF": "Djiboutian Franc"
,"SZL": "Swazi Lilangeni"
,"THB": "Thai Baht"
,"XAF": "CFA Franc BEAC"
,"BND": "Brunei Dollar"
,"ISK": "Icelandic Króna"
,"UYU": "Uruguayan Peso"
,"NIO": "Nicaraguan Córdoba"
,"LAK": "Laotian Kip"
,"SYP": "Syrian Pound"
,"MAD": "Moroccan Dirham"
,"MZN": "Mozambican Metical"
,"PHP": "Philippine Peso"
,"ZAR": "South African Rand"
,"NPR": "Nepalese Rupee"
,"ZWL": "Zimbabwean Dollar"
,"NGN": "Nigerian Naira"
,"CRC": "Costa Rican Colón"
,"AED": "United Arab Emirates Dirham"
,"GBP": "British Pound Sterling"
,"MWK": "Malawian Kwacha"
,"LKR": "Sri Lankan Rupee"
,"PKR": "Pakistani Rupee"
,"HUF": "Hungarian Forint"
,"BMD": "Bermudan Dollar"
,"LSL": "Lesotho Loti"
,"MNT": "Mongolian Tugrik"
,"AMD": "Armenian Dram"
,"UGX": "Ugandan Shilling"
,"QAR": "Qatari Rial"
,"XDR": "Special Drawing Rights"
,"JMD": "Jamaican Dollar"
,"GEL": "Georgian Lari"
,"SHP": "Saint Helena Pound"
,"AFN": "Afghan Afghani"
,"SBD": "Solomon Islands Dollar"
,"KPW": "North Korean Won"
,"TRY": "Turkish Lira"
,"BDT": "Bangladeshi Taka"
,"YER": "Yemeni Rial"
,"HTG": "Haitian Gourde"
,"XOF": "CFA Franc BCEAO"
,"MGA": "Malagasy Ariary"
,"ANG": "Netherlands Antillean Guilder"
,"LRD": "Liberian Dollar"
,"RWF": "Rwandan Franc"
,"NOK": "Norwegian Krone"
,"MOP": "Macanese Pataca"
,"INR": "Indian Rupee"
,"MXN": "Mexican Peso"
,"CZK": "Czech Republic Koruna"
,"TJS": "Tajikistani Somoni"
,"BTC": "Bitcoin"
,"BTN": "Bhutanese Ngultrum"
,"COP": "Colombian Peso"
,"TMT": "Turkmenistani Manat"
,"MUR": "Mauritian Rupee"
,"IDR": "Indonesian Rupiah"
,"HNL": "Honduran Lempira"
,"XPF": "CFP Franc"
,"FJD": "Fijian Dollar"
,"ETB": "Ethiopian Birr"
,"PEN": "Peruvian Nuevo Sol"
,"BZD": "Belize Dollar"
,"ILS": "Israeli New Sheqel"
,"DOP": "Dominican Peso"
,"GGP": "Guernsey Pound"
,"MDL": "Moldovan Leu"
,"BSD": "Bahamian Dollar"
,"SEK": "Swedish Krona"
,"ZMK": "Zambian Kwacha (pre-2013)"
,"JEP": "Jersey Pound"
,"AUD": "Australian Dollar"
,"SRD": "Surinamese Dollar"
,"CUP": "Cuban Peso"
,"CLF": "Chilean Unit of Account (UF)"
,"BBD": "Barbadian Dollar"
,"KMF": "Comorian Franc"
,"KRW": "South Korean Won"
,"GMD": "Gambian Dalasi"
,"VEF": "Venezuelan Bolívar Fuerte"
,"IMP": "Manx pound"
,"CUC": "Cuban Convertible Peso"
,"CLP": "Chilean Peso"
,"ZMW": "Zambian Kwacha"
,"EUR": "Euro"
,"CDF": "Congolese Franc"
,"XCD": "East Caribbean Dollar"
,"KZT": "Kazakhstani Tenge"
,"RUB": "Russian Ruble"
,"XAG": "Silver (troy ounce)"
,"TTD": "Trinidad and Tobago Dollar"
,"OMR": "Omani Rial"
,"BRL": "Brazilian Real"
,"MMK": "Myanma Kyat"
,"PLN": "Polish Zloty"
,"PYG": "Paraguayan Guarani"
,"KES": "Kenyan Shilling"
,"SVC": "Salvadoran Colón"
,"MKD": "Macedonian Denar"
,"AZN": "Azerbaijani Manat"
,"TOP": "Tongan Paʻanga"
,"MVR": "Maldivian Rufiyaa"
,"VUV": "Vanuatu Vatu"
,"GNF": "Guinean Franc"
,"WST": "Samoan Tala"
,"IQD": "Iraqi Dinar"
,"ERN": "Eritrean Nakfa"
,"BAM": "Bosnia-Herzegovina Convertible Mark"
,"SCR": "Seychellois Rupee"
,"CAD": "Canadian Dollar"
,"CVE": "Cape Verdean Escudo"
,"KWD": "Kuwaiti Dinar"
,"BIF": "Burundian Franc"
,"PGK": "Papua New Guinean Kina"
,"SOS": "Somali Shilling"
,"TWD": "New Taiwan Dollar"
,"SGD": "Singapore Dollar"
,"UZS": "Uzbekistan Som"
,"STD": "São Tomé and Príncipe Dobra"
,"IRR": "Iranian Rial"
,"CNY": "Chinese Yuan"
,"SLL": "Sierra Leonean Leone"
,"TND": "Tunisian Dinar"
,"GYD": "Guyanaese Dollar"
,"NZD": "New Zealand Dollar"
,"FKP": "Falkland Islands Pound"
,"LVL": "Latvian Lats"
,"USD": "United States Dollar"
,"KGS": "Kyrgystani Som"
,"ARS": "Argentine Peso"
,"RON": "Romanian Leu"
,"GTQ": "Guatemalan Quetzal"
,"RSD": "Serbian Dinar"
,"BHD": "Bahraini Dinar"
,"JPY": "Japanese Yen"
,"SDG": "Sudanese Pound"
,"XAU": "Gold (troy ounce)"
}
